Enhance configure script

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+source zsh/.config/zsh/.zprofile
+
 if ! test -f /usr/local/bin/pinentry-mac; then
   sudo ln -ns `which pinentry-mac` /usr/local/bin/pinentry-mac
 fi
@@ -7,15 +9,20 @@ fi
 mkdir -p ~/.config/zsh && stow zsh
 mkdir -p ~/.config/git && stow git
 mkdir -p ~/.config/btdt && stow btdt
-gpg -k && stow gnupg && keybase pgp pull-private --all && rm ~/.gnupg/public-keys.d/.\#*
+gpg -k && stow gnupg && keybase pgp pull-private --all
+if [ ! $? -eq 0 ]; then
+    # sometimes import failed
+    keybase pgp pull-private --all
+fi
+rm ~/.gnupg/public-keys.d/.\#*
 stow vim && vim -c "PlugInstall" -c "q" -c "q"
 stow starship
 stow maven
 
 mkdir -p ~/.config/jenv/versions
-ln -ns /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home ~/.config/jenv/versions/AdoptiumTemurin-1.8
-ln -ns /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home ~/.config/jenv/versions/AdoptiumTemurin-11
-ln -ns /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home ~/.config/jenv/versions/AdoptiumTemurin-17
-ln -ns /Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home ~/.config/jenv/versions/AdoptiumTemurin-21
-ln -ns /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home ~/.config/jenv/versions/Apple-1.6
+ln -nsf /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home ~/.config/jenv/versions/AdoptiumTemurin-1.8
+ln -nsf /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home ~/.config/jenv/versions/AdoptiumTemurin-11
+ln -nsf /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home ~/.config/jenv/versions/AdoptiumTemurin-17
+ln -nsf /Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home ~/.config/jenv/versions/AdoptiumTemurin-21
+ln -nsf /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home ~/.config/jenv/versions/Apple-1.6
 echo "AdoptiumTemurin-1.8" > ~/.config/jenv/version
